# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"


# Setup
title:               Marios Papachristou
tagline:             'Personal Homepage'
description:         'Hello! This is the personal homepage of Marios Papachristou built with Jekyll and the Lanyon Theme. For more visit <a href="https://github.com/papachristoumarios">my GitHub account</a>'
url:                 http://github.com/papachristoumarios
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Marios Papachristou
  url:               https://github.com/papachristoumarios
  email:             papachristoumarios@gmail.com

# Custom vars
version:             1.0.0
